# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: API Particulier
email: contact@particulier.api.gouv.fr
description: > # this means to ignore newlines until "baseurl:"
  Simplifier les démarches des particuliers en récupérant pour eux
  leurs données et documents administratifs.

# The baseurl option is set for links (especialy assets links) to work
# with Github pages. For the production environment the website is built
# with the `--baseurl ''` option so the site can be served from the root
# domain. This way links will work in both environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://particulier.api.gouv.fr" # the base hostname & protocol for your site, e.g. http://example.com

cgu_file_link: 'https://entreprise.api.gouv.fr/assets/cgu.pdf'
signup_url: 'https://signup.particulier.api.gouv.fr'
twitter_username: jekyllrb
github_username:  jekyll

destination: ./_site

permalink: pretty

# Collections
collections:
  providers:
  available_data:
    output: true
  use_cases:
      output: true

# API Entreprise specific variables
api_documentation_url: https://doc.entreprise.api.gouv.fr
dashboard_url: https://dashboard.entreprise.api.gouv.fr
gitbook_url: https://etalab-entreprise.gitbook.io/api-entreprise-documentation-infra
signup_url: https://signup.particulier.api.gouv.fr

# Build settings
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-target-blank

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

sass:
  style: compressed
