# config.yml

backend:
  name: git-gateway
  repo: betagouv/particulier.api.gouv.fr
  branch: gh-pages
  site_domain: optimistic-kirch-8b7706.netlify.app
media_folder: "assets/uploads"
collections:
  - name: "pages"
    label: "Pages"
    folder: "pages/"
    fields:
      - { name: Title }
  - name: "endpoint"
    label: "Endpoint"
    folder: "_collections/catalogue"
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: "Categorie", name: "category", widget: "string" }
      - { label: "Nom", name: "title", widget: "string" }
      - { label: "Référence", name: "reference", widget: "string" }
